Configurations:
  - JeaRoles

JeaRoles:
  Roles:

    - Path: C:\Program Files\WindowsPowerShell\Modules\Demos\RoleCapabilities\AdManagementGroups.psrc
      ModulesToImport:
      - ActiveDirectory
      VisibleFunctions:
      - New-xAdGroup
      - Remove-xAdGroup
      FunctionDefinitions:
      - Name: New-xAdGroup
        ScriptBlock: |
          param (
              [Parameter(ParameterSetName = 'Default')]
              [string]$Path = "CN=Users,DC=contoso,DC=com",
              
              [Parameter(Mandatory, ParameterSetName = 'Default')]
              [string]$Name,
              
              [Parameter(ParameterSetName = 'Default')]
              [string]$Description,

              [Parameter(ParameterSetName = 'Default')]
              [ValidateSet('DomainLocal', 'Universal', 'Global')]
              [string]$GroupScope = 'Security',

              [Parameter(ParameterSetName = 'Default')]
              [ValidateSet('Distribution', '')]
              [string]$GroupCategory
          )
    
          "New-ADGroup -Path $Path -Name $Name -GroupType $GroupType -Description $Description" | Out-File -FilePath C:\Commands.txt -Append
          New-ADGroup -Path $Path -Name $Name -GroupScope $GroupScope -GroupCategory $GroupCategory -Description $Description
      - Name: Remove-xAdGroup
        ScriptBlock: |
          param (
              [Parameter(Mandatory, ParameterSetName = 'Default')]
              [string]$Identity
          )
    
          "Remove-ADGroup -Identity $Identity -Confirm:$false" | Out-File -FilePath C:\Commands.txt -Append
          Remove-ADGroup -Identity $Identity -Confirm:$false
