Configurations:
  - JeaRoles

JeaRoles:
  Roles:

    - Path: C:\Program Files\WindowsPowerShell\Modules\Demos\RoleCapabilities\AdManagementUsers.psrc
      ModulesToImport:
      - ActiveDirectory
      VisibleFunctions:
      - New-xAdUser
      - Remove-xAdUser
      FunctionDefinitions:
      - Name: New-xAdUser
        ScriptBlock: |
          param (
              [Parameter(ParameterSetName = 'Default')]
              [string]$Path = "CN=Users,DC=contoso,DC=net",
              
              [Parameter(Mandatory, ParameterSetName = 'Default')]
              [string]$Name,
              
              [Parameter(ParameterSetName = 'Default')]
              [string]$GivenName,
    
              [Parameter(ParameterSetName = 'Default')]
              [string]$Surname,
    
              [Parameter(Mandatory, ParameterSetName = 'Default')]
              [securestring]$AccountPassword,

              [Parameter(Mandatory, ParameterSetName = 'FileUpload')]
              [string]$FilePath,

              [Parameter(ParameterSetName = 'FileUpload')]
              [switch]$DoNotArchiveInputFile
          )
    
          if ($PSCmdlet.ParameterSetName -eq 'Default') {
              New-ADUser @PSBoundParameters
              "User account '$Name' created in '$Path'"
          }
          elseif ($PSCmdlet.ParameterSetName -eq 'FileUpload') {
              $data = Import-Csv -Path $FilePath -Delimiter ';'
              $data | New-ADUser
              
              if (-not $DoNotArchiveInputFile) {
                  Remove-Item -Path $FilePath -Force
              }
              "Created $($data.Count) user accounts in AD."
          }
          else {
              Write-Error 'Unknown parameter set'
          }
      - Name: Remove-xAdUser
        ScriptBlock: |
          param (
              [Parameter(Mandatory, ParameterSetName = 'Default')]
              [string]$Identity,

              [Parameter(Mandatory, ParameterSetName = 'FileUpload')]
              [string]$FilePath,

              [Parameter(ParameterSetName = 'FileUpload')]
              [switch]$DoNotArchiveInputFile
          )
    
          if ($PSCmdlet.ParameterSetName -eq 'Default') {
              Remove-ADUser -Identity $Identity -Confirm:$false
              "User account '$Name' has been removed."
          }
          elseif ($PSCmdlet.ParameterSetName -eq 'FileUpload') {
              $data = Import-Csv -Path $FilePath -Delimiter ';'
              $data.Identity | Remove-ADUser -Confirm:$false
              if (-not $DoNotArchiveInputFile) {
                  Remove-Item -Path $FilePath -Force
              }
              "Removed $($data.Count) user accounts from AD."
          }
          else {
              Write-Error 'Unknown parameter set'
          }
