Configurations:
  - JeaRoles

JeaRoles:
  Roles:

    - Path: C:\Program Files\WindowsPowerShell\Modules\Demos\RoleCapabilities\AdManagementComputers.psrc
      ModulesToImport:
      - ActiveDirectory
      VisibleFunctions:
      - New-xAdComputer
      - Remove-xAdComputer
      FunctionDefinitions:
      - Name: New-xAdComputer
        ScriptBlock: |
          param (
              [Parameter(ParameterSetName = 'Default')]
              [string]$Path = "CN=Users,$((Get-ADRootDSE).defaultNamingContext)",
              
              [Parameter(Mandatory, ParameterSetName = 'Default')]
              [string]$Name
          )
    
          "New-ADComputer -Path $Path -Name $Name" | Out-File -FilePath C:\Commands.txt -Append
          New-ADComputer -Path $Path -Name $Name
      - Name: Remove-xAdComputer
        ScriptBlock: |
          param (
              [Parameter(Mandatory, ParameterSetName = 'Default')]
              [string]$Identity
          )
    
          "Remove-ADComputer -Identity $Identity -Confirm:$false" | Out-File -FilePath C:\Commands.txt -Append
          Remove-ADComputer -Identity $Identity -Confirm:$false
