Configurations:
  - JeaRoles

JeaRoles:
  Roles:

    - Path: C:\Program Files\WindowsPowerShell\Modules\Demos\RoleCapabilities\AdManagement.psrc
      ModulesToImport:
      - ActiveDirectory
      - DnsServer
      VisibleFunctions:
      - New-xDnsRecord
      - New-xAdUser
      - Remove-xAdUser
      FunctionDefinitions:
      - Name: New-xDnsRecord
        ScriptBlock: |
          param (
              [Parameter(Mandatory)]
              [string]$IPv4Address,
              
              [Parameter(Mandatory)]
              [string]$Name,
              
              [Parameter(Mandatory)]
              [string]$ZoneName,
    
              [string]$ComputerName = ((Get-ADDomainController).HostName)
          )
          Add-DnsServerResourceRecordA @PSBoundParameters
      - Name: New-xAdUser
        ScriptBlock: |
          param (
              [Parameter(ParameterSetName = 'Default')]
              [string]$Path = "CN=Users,$((Get-ADRootDSE).defaultNamingContext)",
              
              [Parameter(Mandatory, ParameterSetName = 'Default')]
              [string]$Name,
              
              [Parameter(ParameterSetName = 'Default')]
              [string]$GivenName,
    
              [Parameter(ParameterSetName = 'Default')]
              [string]$Surname,
    
              [Parameter(Mandatory, ParameterSetName = 'Default')]
              [securestring]$AccountPassword
          )
    
          "New-ADUser -Path $Path -AccountPassword $AccountPassword -Name $Name -GivenName $GivenName -Surname $Surname -Enabled $true" | Out-File -FilePath C:\Commands.txt -Append
          New-ADUser -Path $Path -AccountPassword $AccountPassword -Name $Name -GivenName $GivenName -Surname $Surname -Enabled $true
      - Name: Remove-xAdUser
        ScriptBlock: |
          param (
              [Parameter(Mandatory, ParameterSetName = 'Default')]
              [string]$Identity
          )
    
          "Remove-ADUser -Identity $Identity -Confirm:$false" | Out-File -FilePath C:\Commands.txt -Append
          Remove-ADUser -Identity $Identity -Confirm:$false
