Configurations:
  - JeaRoles

JeaRoles:
  Roles:

    - Path: C:\Program Files\WindowsPowerShell\Modules\Demos\RoleCapabilities\DhcpManagement.psrc
      ModulesToImport:
      - DhcpServer
      VisibleFunctions:
      - New-xDhcpReservation
      FunctionDefinitions:
      - Name: New-xDhcpReservation
        ScriptBlock: |
          param (
              [Parameter(Mandatory, ParameterSetName = 'Default')]
              [string]$ScopeId,

              [Parameter(Mandatory, ParameterSetName = 'Default')]
              [string]$IPAddress,

              [Parameter(Mandatory, ParameterSetName = 'Default')]
              [string]$ClientId,

              [Parameter(Mandatory, ParameterSetName = 'Default')]
              [string]$Name,

              [Parameter(Mandatory, ParameterSetName = 'Default')]
              [string]$FilePath,

              [Parameter(ParameterSetName = 'FileUpload')]
              [switch]$DoNotArchiveInputFile
          )

          if ($PSCmdlet.ParameterSetName -eq 'Default') {
              Add-DhcpServerv4Reservation @PSBoundParameters
              "DHCP Reservation created"
          }
          elseif ($PSCmdlet.ParameterSetName -eq 'FileUpload') {
              $data = Get-Content -Path $FilePath | ConvertFrom-Csv -Delimiter ';'
              $data | Add-DhcpServerv4Reservation
              if (-not $DoNotArchiveInputFile) {
                  Remove-Item -Path $FilePath -Force
              }
              "Created $($data.Count) DHCP reservations."
          }
          else {
              Write-Error 'Unknown parameter set'
          }
