Configurations:
  - JeaRoles

JeaRoles:
  Roles:

    - Path: C:\Program Files\WindowsPowerShell\Modules\Demos\RoleCapabilities\DnsManagementRecords.psrc
      ModulesToImport:
      - DnsServer
      VisibleFunctions:
      - New-xDnsRecord
      FunctionDefinitions:
      - Name: New-xDnsRecord
        ScriptBlock: |
          param (
              [Parameter(ParameterSetName = 'Default')]
              [string]$ZoneName = "contoso.com",
              
              [Parameter(Mandatory, ParameterSetName = 'Default')]
              [string]$Name,
              
              [Parameter(ParameterSetName = 'Default')]
              [string]$IPv4Address,
    
              [Parameter(ParameterSetName = 'Default')]
              [string]$DnsServerName,
    
              [Parameter(Mandatory, ParameterSetName = 'FileUpload')]
              [string]$FilePath,

              [Parameter(ParameterSetName = 'FileUpload')]
              [switch]$DoNotArchiveInputFile
          )
    
          if ($PSCmdlet.ParameterSetName -eq 'Default') {
              Add-DnsServerResourceRecordA -Name $Name -IPv4Address $IPv4Address -ZoneName $ZoneName -ComputerName $DnsServerName
          }
          elseif ($PSCmdlet.ParameterSetName -eq 'FileUpload') {
              Write-Error 'Not implemented yet.'
          }
          else {
              Write-Error 'Unknown parameter set.'
          }
