ConvertFrom-StringData @'
    ValidatingPath                  = Validating Path: {0} (JRC0001)
    CheckPsrcExtension              = Checking file extension is psrc for: {0} (JRC0002)
    NotPsrcExtension                = Doesn't have psrc extension for: {0} (JRC0003)
    CheckParentFolder               = Checking parent forlder is RoleCapabilities for: {0} (JRC0004)
    NotRoleCapabilitiesParent       = Parent folder isn't RoleCapabilities for: {0} (JRC0005)
    ValidePsrcPath                  = Path is a valid psrc path. Returning true. (JRC0006)
    FunctionDefinedNotVisible       = Function defined but not visible to Role Configuration: {0} (JRC0007)
    InvalidPath                     = Invalid path specified. It must point to a Module folder, be a psrc file and the parent folder must be called RoleCapabilities. (JRC0008)
    ReasonFileNotFound              = File {0} is absent but it ought to be present. (JRC0009)
    ReasonEnsure                    = File {0} is present but it ought to be absent. (JRC0010)
    ReasonModulesToImport           = ModulesToImport hasn't got the good values. (JRC0011)
    ReasonVisibleAliases            = VibibleAliases hasn't got the good values. (JRC0012)
    ReasonVisibleCmdlets            = VisibleCmdlets hasn't got the good values. (JRC0013)
    ReasonVisibleFunctions          = VisibleFunctions hasn't got the good values. (JRC0014)
    ReasonVisibleExternalCommands   = VisibleExternalCommands hasn't got the good values. (JRC0015)
    ReasonVisibleProviders          = VisibleProviders hasn't got the good values. (JRC0010)
    ReasonScriptsToProcess          = ScriptsToProcess hasn't got the good values. (JRC0016)
    ReasonAliasDefinitions          = AliasDefinitions hasn't got the good values. (JRC0017)
    ReasonFunctionDefinitions       = FunctionDefinitions hasn't got the good values. (JRC0018)
    ReasonVariableDefinitions       = VariableDefinitions hasn't got the good values. (JRC0019)
    ReasonEnvironmentVariables      = EnvironmentVariables hasn't got the good values. (JRC0020)
    ReasonTypesToProcess            = TypesToProcess hasn't got the good values. (JRC0021)
    ReasonFormatsToProcess          = FormatsToProcess hasn't got the good values. (JRC0022)
    ReasonDescription               = Description of role must be : {0} (JRC0023)
    ReasonAssembliesToLoad          = AssembliesToLoad hasn't got the good values. (JRC0024)
'@
